/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as PaseRouteImport } from './routes/pase'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ApiPublicPostalPostalCodeRouteImport } from './routes/api/public/postal.$postalCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const PaseRoute = PaseRouteImport.update({
  id: '/pase',
  path: '/pase',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostalPostalCodeRoute =
  ApiPublicPostalPostalCodeRouteImport.update({
    id: '/api/public/postal/$postalCode',
    path: '/api/public/postal/$postalCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/confirmar': typeof ConfirmarRoute
  '/pase': typeof PaseRoute
  '/registro': typeof RegistroRoute
  '/api/public/postal/$postalCode': typeof ApiPublicPostalPostalCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/confirmar': typeof ConfirmarRoute
  '/pase': typeof PaseRoute
  '/registro': typeof RegistroRoute
  '/api/public/postal/$postalCode': typeof ApiPublicPostalPostalCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/confirmar': typeof ConfirmarRoute
  '/pase': typeof PaseRoute
  '/registro': typeof RegistroRoute
  '/api/public/postal/$postalCode': typeof ApiPublicPostalPostalCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/confirmar'
    | '/pase'
    | '/registro'
    | '/api/public/postal/$postalCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/confirmar'
    | '/pase'
    | '/registro'
    | '/api/public/postal/$postalCode'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/confirmar'
    | '/pase'
    | '/registro'
    | '/api/public/postal/$postalCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  ConfirmarRoute: typeof ConfirmarRoute
  PaseRoute: typeof PaseRoute
  RegistroRoute: typeof RegistroRoute
  ApiPublicPostalPostalCodeRoute: typeof ApiPublicPostalPostalCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pase': {
      id: '/pase'
      path: '/pase'
      fullPath: '/pase'
      preLoaderRoute: typeof PaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postal/$postalCode': {
      id: '/api/public/postal/$postalCode'
      path: '/api/public/postal/$postalCode'
      fullPath: '/api/public/postal/$postalCode'
      preLoaderRoute: typeof ApiPublicPostalPostalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  ConfirmarRoute: ConfirmarRoute,
  PaseRoute: PaseRoute,
  RegistroRoute: RegistroRoute,
  ApiPublicPostalPostalCodeRoute: ApiPublicPostalPostalCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
